### ISSUE TITLE
Scope: RFCs we update, not "CC in general"

### ISSUE THREAD

**Issue by mwelzl** [mwelzl/draft-ccwg-ratelimited-increase#18]
[At IETF-119, concerns were raised](https://datatracker.ietf.org/meeting/119/materials/minutes-119-ccwg-01) about this document being specific to the "cwnd", and not applying to (primarily) rate-based controls such as BBR.

This may be due to text such as: "senders using a congestion controlled transport protocol... (MUST / SHOULD ...)"

I think we should update the wording to narrow the scope to specifically be about the updated RFCs only.

**Comment by gorryfair** [comment]
Or we can update the published RFCs, and then note in a separate section that rate-based methods (such as BBR) have similar needs, and explain a little how cwnd comstrains the rate based on measured CC information. There's no RFC for BBR, so a (sub)section in this style with guidance would perhaps be more appropriate than trying to craft words around the current rev of the ID(s)?

**Comment by mwelzl** [comment]
We can combine this with clarifications around pacing.
