### ISSUE TITLE
Trim the list of possible RFCs to update

### ISSUE THREAD

**Issue by mwelzl** [mwelzl/draft-ccwg-ratelimited-increase#19]
... because [it prompted the comment](https://datatracker.ietf.org/meeting/119/materials/minutes-119-ccwg-01): "We should remind ourselves that an option is to declare some specs as historic, because it doesn't have deployment. Rather than updating we may just say an RFC is historic, rather than waste effort".

**Comment by gorryfair** [comment]
I agree we ought to trim the list!!
However, to obsolete a spec., we'd need to discuss if the method is deployed/implemented - and that might be a hard call to identify dead work or work that needs to be obsoleted for stability. At least I'd avoid doing that work.
I think we could flip this and say "these specific specs are deployed..." and hence continue to say how to update them in this draft. 
We might then avoid to comment on the status of RFCs that *could perhaps* have been implemented somewhere, but where can't see significant momentum at present.

**Comment by mwelzl** [comment]
Yes, just stop mentioning them.
