### ISSUE TITLE
github.io link is not working

### ISSUE THREAD

**Issue by mohittahiliani** [mwelzl/draft-ccwg-ratelimited-increase#24]
The following link in the note gives a 404:

https://mwelzl.github.io/draft-ccwg-constrained-increase/draft-welzl-ccwg-constrained-increase.html

**Comment by mwelzl** [comment]
Thanks!  That must be to do with the renaming that we did - from "constrained" to ratelimited".  I see, this must be the link in the draft itself?  (easy to fix, and will, if that's all !)  Or where else have you seen that URL?

**Comment by mwelzl** [comment]
( just to be clear: the correct one should be:  https://mwelzl.github.io/draft-ccwg-ratelimited-increase/draft-welzl-ccwg-ratelimited-increase.html  )

**Comment by mohittahiliani** [comment]
> Thanks! That must be to do with the renaming that we did - from "constrained" to ratelimited". I see, this must be the link in the draft itself? (easy to fix, and will, if that's all !) Or where else have you seen that URL?

Yes, it's in the draft. The link with "ratelimited" works.
