### ISSUE TITLE
maxFS should only be valid for one RTT => fixed by master, if you agree?

### ISSUE THREAD

**Issue by mwelzl** [mwelzl/draft-ccwg-ratelimited-increase#30]
IETF-120:

- Neal: The MaxFS could seem to be over a time longer than an RTT, so we could use evidence from minutes, hours, days ago to justify the increase of the cwnd now. I wonder if we want to structure it so you can only use the flight size in the most recent round trip time, that's how the Linux code is structured.
- Michael: New congestion window validation (CWV) controls this case, which is an Experimental spec. Either way this is just a SHOULD.

We can point at new-cwv more than we already do, but it's interesting that Neal says that "that's how the Linux code is structured". We should check how Linux pulls this off. Hint to self: see the function: tcp_is_cwnd_limited

**Comment by mwelzl** [comment]
Neal must have thought: because this isn't done in CA in Linux?  I don't know - the Linux check is here:
https://elixir.bootlin.com/linux/v6.11.3/source/include/net/tcp.h#L1387
and it's a check against max_packets_out, which is only written here:
https://elixir.bootlin.com/linux/v6.11.3/source/net/ipv4/tcp_output.c#L1930
which just implements the "max" function.

**Comment by mwelzl** [comment]
Ahhh, I closed this by accident, by issuing a push to master, not a new branch!   Please take a look at rule 3 and the last paragraph in section 3, both new - and if you dislike, propose a fix (or push to master like I did   :-)  )

**Comment by nealcardwell** [comment]
> Neal must have thought: because this isn't done in CA in Linux? I don't know - the Linux check is here: https://elixir.bootlin.com/linux/v6.11.3/source/include/net/tcp.h#L1387 and it's a check against max_packets_out, which is only written here: https://elixir.bootlin.com/linux/v6.11.3/source/net/ipv4/tcp_output.c#L1930 which just implements the "max" function.

It doesn't just implement a "max" function. :-)

Note that the expression !before(tp->snd_una, tp->cwnd_usage_seq) checks whether a round trip has elapsed. If a round trip has elapsed, then it sets tp->max_packets_out = tp->packets_out. That means that tp->max_packets_out only reflects the number of packets out in the network over the time scale of the last round trip.

**Comment by mwelzl** [comment]
Aha!!!  Thanks!

And: guilty as charged!   I admit, when I looked, I reacted to seeing this line with its "snd_una, ..." by thinking: "yeah, yeah, some seqno check, not so important" and then missed this. My sloppiness wasted your time here. I'm sorry and will try to be more careful in the future!

**Comment by mwelzl** [comment]
So it seems the fix to master is ok [private email among the authors, and also to the authors]. Closing this.
