### ISSUE TITLE
Security Consideration.

### ISSUE THREAD

**Issue by gorryfair** [mwelzl/draft-ccwg-ratelimited-increase#4]
I agree with the content of the security considerations section, but I am unsure that this is a real security issue.

I think it might be wiser to move this text and assert something like: 

While congestion control issues could result in unwanted competing traffic, they do not directly result in security considerations. Transport protocols that provide authentication (including those using encryption) or that are carried over protocols that provide authentication, can protect the congestion control mechanisms from network attack.

**Comment by mwelzl** [comment]
Change applied in the version for the new repo

**Comment by mwelzl** [comment]
Sorry, I closed this as I thought I need to make a new repo. Anyway, I did address this with a push to master - @gorryfair  could you check, and close the issue if you agree with my change?

**Comment by mwelzl** [comment]
ping :-)   this change is implemented, can we close this issue?
