### ISSUE TITLE
Avoid over-use of the word "limit" in rules

### ISSUE THREAD

**Issue by mwelzl** [mwelzl/draft-ccwg-ratelimited-increase#40]
...as in "limit with limit(..)"  - especially in rule #3 where it's a different limit.

**Comment by mohittahiliani** [comment]
In my opinion, the beginning of Section 3 can be simplified as below:

When FlightSize < cwnd, regardless of the current state of a congestion control algorithm, senders using a congestion-controlled transport protocol:

1. MUST include a constraint on the growth of cwnd
2. SHOULD cap cwnd to be no larger than limit(maxFS)
3. MAY restrict maxFS as min(maxFS, pipeACK), using "pipeACK" as defined in [RFC7661]

Note: In rule #2, the function limit() determines the maximum cwnd value possible in one RTT based on the congestion control algorithm and the maxFS parameter.

**Comment by mwelzl** [comment]
I prefer the phrasing proposed by @mohittahiliani  - others?
