### ISSUE TITLE
Implementation Note in A.1.1.

### ISSUE THREAD

**Issue by mohittahiliani** [mwelzl/draft-ccwg-ratelimited-increase#43]
The 'Implementation Note' in A.1.1. cited from Page 8 of RFC 5681 might require some more explanation because this note is primarily related to ssthresh in RFC 5681. It would be good to add the details of how this could lead to the growth of cwnd when sender is rate-limited.

**Comment by mwelzl** [comment]
The first two paragraphs of A 1.1 can be deleted, and the word "also" removed from the following sentence. Then this is easier to read. Thanks!
