### ISSUE TITLE
Fix Linux kernel text

### ISSUE THREAD

**Issue by mwelzl** [mwelzl/draft-ccwg-ratelimited-increase#5]
is_cwnd_limited implements what we want, just "hard-coded" and for slow start only, since kernel 3.16 which was published in August 2014.

See: https://elixir.bootlin.com/linux/v3.16/source/include/net/tcp.h#L985

The current text mis-represents Linux, and also talks about a weird old version number.

**Comment by gorryfair** [comment]
Good find, and we should cite and fix in a PR:-)

**Comment by mwelzl** [comment]
Will do *very* soon, promise!
